export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  // {
  //   title: "Company",
  //   links: [
  //     { title: "Events", url: "/" },
  //     { title: "Blog", url: "/" },
  //     { title: "Podcast", url: "/" },
  //     { title: "Invite a friend", url: "/" },
  //   ],
  // },
  {
    title: "Socials",
    links: [
      // { title: "Discord", url: "/" },
      {
        title: "Whatsapp",
        url: "https://api.whatsapp.com/send?phone=6282145541170",
      },
      // { title: "Twitter", url: "/" },
      { title: "Email", url: "mailto:admin@bali88rent.com" },
    ],
  },
];

export const carsData = [
  {
    id: 1,
    image: "/assets/ayla.png",
    type: "Ayla",
    brand: "Daihatsu",
    model: "Ayla A/T",
    fuel: "Bensin",
    price: "250.000",
  },
  {
    id: 2,
    image: "/assets/agya.png",
    type: "Agya",
    brand: "Toyota",
    model: "Agya M/T",
    fuel: "Bensin",
    price: "250.000",
  },
  {
    id: 3,
    image: "/assets/brio.png",
    type: "Brio",
    brand: "Honda",
    model: "Brio RS CVT",
    fuel: "Bensin",
    price: "300.000",
  },
  {
    id: 4,
    image: "/assets/avanza.png",
    type: "New Avanza",
    brand: "Toyota",
    model: "Avanza M/T",
    fuel: "Bensin",
    price: "300.000",
  },
  {
    id: 5,
    image: "/assets/avanza.png",
    type: "New Avanza",
    brand: "Toyota",
    model: "Avanza A/T",
    fuel: "Bensin",
    price: "250.000",
  },
  {
    id: 6,
    image: "/assets/ertiga.png",
    type: "Ertiga",
    brand: "Suzuki",
    model: "Ertiga GX M/T",
    fuel: "Bensin",
    price: "350.000",
  },
  {
    id: 7,
    image: "/assets/avanza.png",
    type: "New Avanza",
    brand: "Toyota",
    model: "Avanza CVT",
    fuel: "Bensin",
    price: "350.000",
  },
  {
    id: 8,
    image: "/assets/xpander.png",
    type: "Xpander",
    brand: "Mitsubishi",
    model: "Xpander",
    fuel: "Bensin",
    price: "350.000",
  },
  {
    id: 9,
    image: "/assets/innova.png",
    type: "Innova Reborn",
    brand: "Toyota",
    model: "Innova Reborn A/T",
    fuel: "Bensin",
    price: "550.000",
  },
  {
    id: 10,
    image: "/assets/innova.png",
    type: "Innova Reborn",
    brand: "Toyota",
    model: "Innova Reborn M/T",
    fuel: "Bensin",
    price: "450.000",
  },
  {
    id: 11,
    image: "/assets/fortuner.png",
    type: "Fortuner + Driver",
    brand: "Toyota",
    model: "Fortuner",
    fuel: "Bensin",
    price: "1.800.000",
  },
  {
    id: 12,
    image: "/assets/alphard.png",
    type: "Alphard + Driver",
    brand: "Toyota",
    model: "Alphard",
    fuel: "Bensin",
    price: "2.500.000",
  },
  {
    id: 13,
    image: "/assets/hiace.png",
    type: "Hiace + Driver",
    brand: "Toyota",
    model: "Hiace Standar",
    fuel: "Bensin",
    price: "1.200.000",
  },
  {
    id: 13,
    image: "/assets/voxy.png",
    type: "Voxy + Driver",
    brand: "Toyota",
    model: "Voxy",
    fuel: "Bensin",
    price: "2.300.000",
  },
  {
    id: 14,
    image: "/assets/elf.png",
    type: "Elf Long + Driver",
    brand: "Isuzu",
    model: "Elf Long",
    fuel: "Bensin",
    price: "1.200.000",
  },
  {
    id: 15,
    image: "/assets/innova.png",
    type: "Innova Reborn + Driver",
    brand: "Toyota",
    model: "Innova Reborn",
    fuel: "Bensin",
    price: "900.000",
  },
  {
    id: 14,
    image: "/assets/avanza.png",
    type: "New Avanza + Driver",
    brand: "Toyota",
    model: "Avanza",
    fuel: "Bensin",
    price: "800.000",
  },
  {
    id: 15,
    image: "/assets/avanza.png",
    type: "Grand New Avanza + Driver",
    brand: "Toyota",
    model: "Avanza",
    fuel: "Bensin",
    price: "650.000",
  },
  {
    id: 15,
    image: "/assets/xpander.png",
    type: "Xpander + Driver",
    brand: "Mitsubishi",
    model: "Xpander",
    fuel: "Bensin",
    price: "800.000",
  },
];
